# config/categories.yaml

# A 类：自循环模块，路径中只出现一次
A:
  - 失业
  - 破产
  - 生病住院
  - 还错卡
  - 工资未发
  - 工程款
  - 否认办理业务
  - 通用原因
  - 他人用款
  - 忘记还款
  - 盗刷

# B 类：可跳转模块
B:
  - 没钱
  - 信息问题
  - 投诉处理
  - 诉求
  - 对抗
  - 不方便接电
  - 敷衍
  - 无法沟通
  - 不方便接电
  


# 自定义模块：覆盖默认出边规则，手动指定候选集
custom:
  模块名:
    # - 语音留言
    # - 身份确认
    # - 告知
    # - 三方
    # - 转告
    # - 承诺还款
    # - 已还款
  
# 不参与概率计算的模块
excluded:
  - 身份确认
  - 语音留言
  - 告知
  - 三方
  - 转告
  - 承诺还款
  - 已还款
  