# config.py

CONFIG = {
    "m0": [
        {
            "name": "M0首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 45,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-无意愿无能力-4w.json",
            "system_dir": "packages/M0_WN_AN/case/systemM0_WN_AN_4w",
            "replace_dir": "packages/M0_WN_AN/case/replaceM0_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10040,
            },
        },
        {
            "name": "M0首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 46,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-无意愿有能力-4w.json",
            "system_dir": "packages/M0_WN_AY/case/systemM0_WN_AY_4w",
            "replace_dir": "packages/M0_WN_AY/case/replaceM0_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 100,
                "end": 199,
                "seed": 10041,
            },
        },
        {
            "name": "M0首催_BP_易跳票客户",
            "enabled": True,
            "seed": 47,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-易跳票客户-4w.json",
            "system_dir": "packages/M0_BP/case/systemM0_BP_4w",
            "replace_dir": "packages/M0_BP/case/replaceM0_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 200,
                "end": 300,
                "seed": 10042,
            },
        },
        {
            "name": "M0首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 48,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-有意愿无能力-4w.json",
            "system_dir": "packages/M0_WY_AN/case/systemM0_WY_AN_4w",
            "replace_dir": "packages/M0_WY_AN/case/replaceM0_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 300,
                "end": 400,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 49,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-有意愿有能力-4w.json",
            "system_dir": "packages/M0_WY_AY/case/systemM0_WY_AY_4w",
            "replace_dir": "packages/M0_WY_AY/case/replaceM0_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 400,
                "end": 500,
                "seed": 10044,
            },
        },
        {
            "name": "M0首催_CR_有投诉风险",
            "enabled": True,
            "seed": 50,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M0-有投诉风险-4w.json",
            "system_dir": "packages/M0_CR/case/systemM0_CR_4w",
            "replace_dir": "packages/M0_CR/case/replaceM0_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 500,
                "end": 600,
                "seed": 10045,
            },
        },
    ],
    "m0_follow": [
        {
            "name": "M0跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 51,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M0_follow_WN_AN/case/systemM0_follow_WN_AN_2w",
            "replace_dir": "packages/M0_follow_WN_AN/case/replaceM0_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 600,
                "end": 700,
                "seed": 10046,
            },
        },
        {
            "name": "M0跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 52,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M0_follow_WN_AY/case/systemM0_follow_WN_AY_2w",
            "replace_dir": "packages/M0_follow_WN_AY/case/replaceM0_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 700,
                "end": 800,
                "seed": 10047,
            },
        },
        {
            "name": "M0跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 53,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-易跳票客户-2w.json",
            "system_dir": "packages/M0_follow_BP/case/systemM0_follow_BP_2w",
            "replace_dir": "packages/M0_follow_BP/case/replaceM0_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 800,
                "end": 900,
                "seed": 10048,
            },
        },
        {
            "name": "M0跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 54,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M0_follow_WY_AN/case/systemM0_follow_WY_AN_2w",
            "replace_dir": "packages/M0_follow_WY_AN/case/replaceM0_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 900,
                "end": 1000,
                "seed": 10049,
            },
        },
        {
            "name": "M0跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 55,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M0_follow_WY_AY/case/systemM0_follow_WY_AY_2w",
            "replace_dir": "packages/M0_follow_WY_AY/case/replaceM0_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1000,
                "end": 1100,
                "seed": 10050,
            },
        },
        {
            "name": "M0跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 56,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M0-follow-有投诉风险-2w.json",
            "system_dir": "packages/M0_follow_CR/case/systemM0_follow_CR_2w",
            "replace_dir": "packages/M0_follow_CR/case/replaceM0_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1100,
                "end": 1200,
                "seed": 10051,
            },
        },
    ],
    "m1": [
        {
            "name": "M1首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 100,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-无意愿无能力-4w.json",
            "system_dir": "packages/M1_WN_AN/case/systemM1_WN_AN_4w",
            "replace_dir": "packages/M1_WN_AN//case/replaceM1_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1200,
                "end": 1300,
                "seed": 10100,
            },
        },
        {
            "name": "M1首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 101,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-无意愿有能力-4w.json",
            "system_dir": "packages/M1_WN_AY/case/systemM1_WN_AY_4w",
            "replace_dir": "packages/M1_WN_AY//case/replaceM1_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1300,
                "end": 1400,
                "seed": 10101,
            },
        },
        {
            "name": "M1首催_BP_易跳票客户",
            "enabled": True,
            "seed": 102,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-易跳票客户-4w.json",
            "system_dir": "packages/M1_BP/case/systemM1_BP_4w",
            "replace_dir": "packages/M1_BP//case/replaceM1_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1400,
                "end": 1500,
                "seed": 10102,
            },
        },
        {
            "name": "M1首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 103,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-有意愿无能力-4w.json",
            "system_dir": "packages/M1_WY_AN/case/systemM1_WY_AN_4w",
            "replace_dir": "packages/M1_WY_AN//case/replaceM1_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1500,
                "end": 1600,
                "seed": 10103,
            },
        },
        {
            "name": "M1首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 104,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-有意愿有能力-4w.json",
            "system_dir": "packages/M1_WY_AY/case/systemM1_WY_AY_4w",
            "replace_dir": "packages/M1_WY_AY//case/replaceM1_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1600,
                "end": 1700,
                "seed": 10104,
            },
        },
        {
            "name": "M1首催_CR_有投诉风险",
            "enabled": True,
            "seed": 105,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M1-有投诉风险-4w.json",
            "system_dir": "packages/M1_CR/case/systemM1_CR_4w",
            "replace_dir": "packages/M1_CR//case/replaceM1_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1700,
                "end": 1800,
                "seed": 10105,
            },
        },
    ],
    "m1_follow": [
        {
            "name": "M1跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 57,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M1_follow_WN_AN/case/systemM1_follow_WN_AN_2w",
            "replace_dir": "packages/M1_follow_WN_AN/case/replaceM1_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1800,
                "end": 1900,
                "seed": 10052,
            },
        },
        {
            "name": "M1跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 58,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M1_follow_WN_AY/case/systemM1_follow_WN_AY_2w",
            "replace_dir": "packages/M1_follow_WN_AY/case/replaceM1_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 1900,
                "end": 2000,
                "seed": 10053,
            },
        },
        {
            "name": "M1跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 59,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-易跳票客户-2w.json",
            "system_dir": "packages/M1_follow_BP/case/systemM1_follow_BP_2w",
            "replace_dir": "packages/M1_follow_BP/case/replaceM1_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2000,
                "end": 2100,
                "seed": 10054,
            },
        },
        {
            "name": "M1跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 60,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M1_follow_WY_AN/case/systemM1_follow_WY_AN_2w",
            "replace_dir": "packages/M1_follow_WY_AN/case/replaceM1_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2100,
                "end": 2200,
                "seed": 10055,
            },
        },
        {
            "name": "M1跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 61,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M1_follow_WY_AY/case/systemM1_follow_WY_AY_2w",
            "replace_dir": "packages/M1_follow_WY_AY/case/replaceM1_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2200,
                "end": 2300,
                "seed": 10056,
            },
        },
        {
            "name": "M1跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 62,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M1-follow-有投诉风险-2w.json",
            "system_dir": "packages/M1_follow_CR/case/systemM1_follow_CR_2w",
            "replace_dir": "packages/M1_follow_CR/case/replaceM1_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2300,
                "end": 2400,
                "seed": 10057,
            },
        },
    ],
    "m2": [
        {
            "name": "M2首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 106,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-无意愿无能力-4w.json",
            "system_dir": "packages/M2_WN_AN/case/systemM2_WN_AN_4w",
            "replace_dir": "packages/M2_WN_AN/case/replaceM2_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2400,
                "end": 2500,
                "seed": 10106,
            },
        },
        {
            "name": "M2首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 107,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-无意愿有能力-4w.json",
            "system_dir": "packages/M2_WN_AY/case/systemM2_WN_AY_4w",
            "replace_dir": "packages/M2_WN_AY/case/replaceM2_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2500,
                "end": 2600,
                "seed": 10107,
            },
        },
        {
            "name": "M2首催_BP_易跳票客户",
            "enabled": True,
            "seed": 108,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-易跳票客户-4w.json",
            "system_dir": "packages/M2_BP/case/systemM2_BP_4w",
            "replace_dir": "packages/M2_BP/case/replaceM2_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2600,
                "end": 2700,
                "seed": 10108,
            },
        },
        {
            "name": "M2首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 109,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-有意愿无能力-4w.json",
            "system_dir": "packages/M2_WY_AN/case/systemM2_WY_AN_4w",
            "replace_dir": "packages/M2_WY_AN/case/replaceM2_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2700,
                "end": 2800,
                "seed": 10109,
            },
        },
        {
            "name": "M2首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 110,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-有意愿有能力-4w.json",
            "system_dir": "packages/M2_WY_AY/case/systemM2_WY_AY_4w",
            "replace_dir": "packages/M2_WY_AY/case/replaceM2_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2800,
                "end": 2900,
                "seed": 10110,
            },
        },
        {
            "name": "M2首催_CR_有投诉风险",
            "enabled": True,
            "seed": 111,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M2-有投诉风险-4w.json",
            "system_dir": "packages/M2_CR/case/systemM2_CR_4w",
            "replace_dir": "packages/M2_CR/case/replaceM2_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 2900,
                "end": 3000,
                "seed": 10111,
            },
        },
    ],
    "m2_follow": [
        {
            "name": "M2跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 63,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M2_follow_WN_AN/case/systemM2_follow_WN_AN_2w",
            "replace_dir": "packages/M2_follow_WN_AN/case/replaceM2_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3000,
                "end": 3100,
                "seed": 10058,
            },
        },
        {
            "name": "M2跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 64,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M2_follow_WN_AY/case/systemM2_follow_WN_AY_2w",
            "replace_dir": "packages/M2_follow_WN_AY/case/replaceM2_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3100,
                "end": 3200,
                "seed": 10058,
            },
        },
        {
            "name": "M2跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 65,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-易跳票客户-2w.json",
            "system_dir": "packages/M2_follow_BP/case/systemM2_follow_BP_2w",
            "replace_dir": "packages/M2_follow_BP/case/replaceM2_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3200,
                "end": 3300,
                "seed": 10059,
            },
        },
        {
            "name": "M2跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 66,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M2_follow_WY_AN/case/systemM2_follow_WY_AN_2w",
            "replace_dir": "packages/M2_follow_WY_AN/case/replaceM2_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3300,
                "end": 3400,
                "seed": 10060,
            },
        },
        {
            "name": "M2跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 67,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M2_follow_WY_AY/case/systemM2_follow_WY_AY_2w",
            "replace_dir": "packages/M2_follow_WY_AY/case/replaceM2_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3400,
                "end": 3500,
                "seed": 10061,
            },
        },
        {
            "name": "M2跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 68,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M2-follow-有投诉风险-2w.json",
            "system_dir": "packages/M2_follow_CR/case/systemM2_follow_CR_2w",
            "replace_dir": "packages/M2_follow_CR/case/replaceM2_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M2_follow/M2_follow_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3500,
                "end": 3600,
                "seed": 10062,
            },
        },
    ],
    "m3_plus": [
        {
            "name": "M3plus首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 112,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-无意愿无能力-4w.json",
            "system_dir": "packages/M3plus_WN_AN/case/systemM3plus_WN_AN_4w",
            "replace_dir": "packages/M3plus_WN_AN/case/replaceM3plus_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3600,
                "end": 3700,
                "seed": 10112,
            },
        },
        {
            "name": "M3plus首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 113,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-无意愿有能力-4w.json",
            "system_dir": "packages/M3plus_WN_AY/case/systemM3plus_WN_AY_4w",
            "replace_dir": "packages/M3plus_WN_AY/case/replaceM3plus_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3700,
                "end": 3800,
                "seed": 10113,
            },
        },
        {
            "name": "M3plus首催_BP_易跳票客户",
            "enabled": True,
            "seed": 114,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-易跳票客户-4w.json",
            "system_dir": "packages/M3plus_BP/case/systemM3plus_BP_4w",
            "replace_dir": "packages/M3plus_BP/case/replaceM3plus_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3800,
                "end": 3900,
                "seed": 10114,
            },
        },
        {
            "name": "M3plus首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 115,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-有意愿无能力-4w.json",
            "system_dir": "packages/M3plus_WY_AN/case/systemM3plus_WY_AN_4w",
            "replace_dir": "packages/M3plus_WY_AN/case/replaceM3plus_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 3900,
                "end": 4000,
                "seed": 10115,
            },
        },
        {
            "name": "M3plus首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 116,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-有意愿有能力-4w.json",
            "system_dir": "packages/M3plus_WY_AY/case/systemM3plus_WY_AY_4w",
            "replace_dir": "packages/M3plus_WY_AY/case/replaceM3plus_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4000,
                "end": 4100,
                "seed": 10116,
            },
        },
        {
            "name": "M3plus首催_CR_有投诉风险",
            "enabled": True,
            "seed": 117,
            "total_cases": 40000,
            "combinations_path": "packages/combinations/combinations-M3plus-有投诉风险-4w.json",
            "system_dir": "packages/M3plus_CR/case/systemM3plus_CR_4w",
            "replace_dir": "packages/M3plus_CR/case/replaceM3plus_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4100,
                "end": 4200,
                "seed": 10117,
            },
        },
    ],
    "m3_plus_follow": [
        {
            "name": "M3_plus跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 69,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M3plus_follow_WN_AN/case/systemM3plus_follow_WN_AN_2w",
            "replace_dir": "packages/M3plus_follow_WN_AN/case/replaceM3plus_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4200,
                "end": 4300,
                "seed": 10063,
            },
        },
        {
            "name": "M3_plus跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 70,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M3plus_follow_WN_AY/case/systemM3plus_follow_WN_AY_2w",
            "replace_dir": "packages/M3plus_follow_WN_AY/case/replaceM3plus_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4300,
                "end": 4400,
                "seed": 10064,
            },
        },
        {
            "name": "M3_plus跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 71,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-易跳票客户-2w.json",
            "system_dir": "packages/M3plus_follow_BP/case/systemM3plus_follow_BP_2w",
            "replace_dir": "packages/M3plus_follow_BP/case/replaceM3plus_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4400,
                "end": 4500,
                "seed": 10065,
            },
        },
        {
            "name": "M3_plus跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 72,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M3plus_follow_WY_AN/case/systemM3plus_follow_WY_AN_2w",
            "replace_dir": "packages/M3plus_follow_WY_AN/case/replaceM3plus_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4500,
                "end": 4600,
                "seed": 10066,
            },
        },
        {
            "name": "M3_plus跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 73,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M3plus_follow_WY_AY/case/systemM3plus_follow_WY_AY_2w",
            "replace_dir": "packages/M3plus_follow_WY_AY/case/replaceM3plus_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4600,
                "end": 4700,
                "seed": 10067,
            },
        },
        {
            "name": "M3_plus跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 74,
            "total_cases": 20000,
            "combinations_path": "packages/combinations/combinations-M3plus-follow-有投诉风险-2w.json",
            "system_dir": "packages/M3plus_follow_CR/case/systemM3plus_follow_CR_2w",
            "replace_dir": "packages/M3plus_follow_CR/case/replaceM3plus_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M3+_follow/M3+_follow_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 4700,
                "end": 4800,
                "seed": 10068,
            },
        },
    ]
}