# config.py
# 同一个模块若有多套 case 配置，写成 list 即可，
# run.py 会依次遍历执行；只有一套时写 dict 也兼容。

CONFIG = {
    "m1": [
        {
            "name": "M1首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 100,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-无意愿无能力-4w.json",
            "system_dir": "packages/M1_WN_AN/case/systemM1_WN_AN_4w",
            "replace_dir": "packages/M1_WN_AN//case/replaceM1_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10100,
            },
        },
        {
            "name": "M1首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 101,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-无意愿有能力-4w.json",
            "system_dir": "packages/M1_WN_AY/case/systemM1_WN_AY_4w",
            "replace_dir": "packages/M1_WN_AY//case/replaceM1_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10101,
            },
        },
        {
            "name": "M1首催_BP_易跳票客户",
            "enabled": True,
            "seed": 102,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-易跳票客户-4w.json",
            "system_dir": "packages/M1_BP/case/systemM1_BP_4w",
            "replace_dir": "packages/M1_BP//case/replaceM1_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10102,
            },
        },
        {
            "name": "M1首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 103,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-有意愿无能力-4w.json",
            "system_dir": "packages/M1_WY_AN/case/systemM1_WY_AN_4w",
            "replace_dir": "packages/M1_WY_AN//case/replaceM1_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10103,
            },
        },
        {
            "name": "M1首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 104,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-有意愿有能力-4w.json",
            "system_dir": "packages/M1_WY_AY/case/systemM1_WY_AY_4w",
            "replace_dir": "packages/M1_WY_AY//case/replaceM1_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10104,
            },
        },
        {
            "name": "M1首催_CR_有投诉风险",
            "enabled": True,
            "seed": 105,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-有投诉风险-4w.json",
            "system_dir": "packages/M1_CR/case/systemM1_CR_4w",
            "replace_dir": "packages/M1_CR//case/replaceM1_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M1/M1_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10105,
            },
        },
    ]
}
