# config.py
# 同一个模块若有多套 case 配置，写成 list 即可，
# run.py 会依次遍历执行；只有一套时写 dict 也兼容。

CONFIG = {
    "m2": [
        {
            "name": "M2首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 106,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-无意愿无能力-4w.json",
            "system_dir": "packages/M2_WN_AN/case/systemM2_WN_AN_4w",
            "replace_dir": "packages/M2_WN_AN/case/replaceM2_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10106,
            },
        },
        {
            "name": "M2首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 107,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-无意愿有能力-4w.json",
            "system_dir": "packages/M2_WN_AY/case/systemM2_WN_AY_4w",
            "replace_dir": "packages/M2_WN_AY/case/replaceM2_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10107,
            },
        },
        {
            "name": "M2首催_BP_易跳票客户",
            "enabled": True,
            "seed": 108,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-易跳票客户-4w.json",
            "system_dir": "packages/M2_BP/case/systemM2_BP_4w",
            "replace_dir": "packages/M2_BP/case/replaceM2_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10108,
            },
        },
        {
            "name": "M2首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 109,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-有意愿无能力-4w.json",
            "system_dir": "packages/M2_WY_AN/case/systemM2_WY_AN_4w",
            "replace_dir": "packages/M2_WY_AN/case/replaceM2_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10109,
            },
        },
        {
            "name": "M2首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 110,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-有意愿有能力-4w.json",
            "system_dir": "packages/M2_WY_AY/case/systemM2_WY_AY_4w",
            "replace_dir": "packages/M2_WY_AY/case/replaceM2_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10110,
            },
        },
        {
            "name": "M2首催_CR_有投诉风险",
            "enabled": True,
            "seed": 111,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M2-有投诉风险-4w.json",
            "system_dir": "packages/M2_CR/case/systemM2_CR_4w",
            "replace_dir": "packages/M2_CR/case/replaceM2_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M2/M2_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10111,
            },
        },
    ]
}
