# config.py

CONFIG = {
    "m0": {
        "name": "M0首催_WN_AN_无意愿无能力",
        "enabled": True,
        "seed": 45,
        "total_cases": 40000,
        "combinations_path": "packages/combinations/combinations-M0-无意愿无能力-4w.json",
        "system_dir": "packages/M0_WN_AN/case/systemM0_4w",
        "replace_dir": "packages/M0_WN_AN/case/replaceM0_4w",
        "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿无能力.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify/replace",
            "start": 0,
            "end": 100,
            "seed": 10043,  
        },
    }
    # "suning_backend": {
    #     "name": "苏宁后端",
    #     "enabled": False,             # 是否启用该业务线
    #     "seed": 32,
    #     "total_cases": 60000,
    #     "combinations_path": "combinations-suning-backend-6w.json",
    #     "system_dir": "new_case/suning-backend/system",
    #     "replace_dir": "new_case/suning-backend/replace",
    #     "prompt_system_path": "scripts_general/case_generator/prompt/backend(M3+)/prompt_template_for_system.txt",
    #     "prompt_replace_path": "scripts_general/case_generator/prompt/prompt_template_for_backbone_replace.txt",
    #     "testify": {
    #         "system_dir": "new_case/testify/system",
    #         "replace_dir": "new_case/testify/replace",
    #         "start": 121,
    #         "end": 140,
    #         "seed": 10040,  
    #     },
    # },
    # "m1": {
    #     "name": "S1首催",
    #     "enabled": True,
    #     "seed": 39,
    #     "total_cases": 60000,
    #     "combinations_path": "combinations-S1-6w.json",
    #     "system_dir": "new_case/S1/systemS1-6w",
    #     "replace_dir": "new_case/S1/replaceS1-6w",
    #     "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-0918.txt",
    #     "prompt_replace_path": "scripts_general/case_generator/prompt/prompt_template_for_backbone_replace.txt",
    #     "testify": {
    #         "system_dir": "new_case/testify/system",
    #         "replace_dir": "new_case/testify/replace",
    #         "start": 200,
    #         "end": 300,
    #         "seed": 10041,  
    #     },
    # },
    # "m1_follow": {
    #     "name": "S1跟催",
    #     "enabled": True,
    #     "seed": 35,
    #     "total_cases": 20000,
    #     "combinations_path": "combinations-S1-follow-2w.json",
    #     "system_dir": "new_case/S1/systemS1-follow-2w",
    #     "replace_dir": "new_case/S1/replaceS1-follow-2w",
    #     "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-follow-0918.txt",
    #     "prompt_replace_path": "scripts_general/case_generator/prompt/prompt_template_for_backbone_replace.txt",
    #     "testify": {
    #         "system_dir": "new_case/testify/system",
    #         "replace_dir": "new_case/testify/replace",
    #         "start": 300,
    #         "end": 400,
    #         "seed": 10042,  
    #     },
    # },
    # "m0": {
    #     "name": "M0未逾期",
    #     "enabled": True,
    #     "seed": 45,
    #     "total_cases": 40000,
    #     "combinations_path": "combinations-M0-4w.json",
    #     "system_dir": "new_case/M0/systemM0_4w",
    #     "replace_dir": "new_case/M0/replaceM0_4w",
    #     "prompt_system_path": "scripts_general/case_generator/prompt/M0_notdue/prompt_template_for_system_M0_new_0918.txt",
    #     "prompt_replace_path": "scripts_general/case_generator/prompt/prompt_template_for_backbone_replace.txt",
    #     "testify": {
    #         "system_dir": "new_case/testify/system",
    #         "replace_dir": "new_case/testify/replace",
    #         "start": 0,
    #         "end": 100,
    #         "seed": 10043,  
    #     },
    # },
    # "m0_follow": {
    #     "name": "M0跟催",
    #     "enabled": True,
    #     "seed": 45,
    #     "total_cases": 10000,
    #     "combinations_path": "combinations-M0-follow-1w.json",
    #     "system_dir": "new_case/M0/systemM0-follow-1w",
    #     "replace_dir": "new_case/M0/replaceM0-follow-1w",
    #     "prompt_system_path": "scripts_general/case_generator/prompt/M0_notdue/prompt_template_for_system_M0_new_follow_0918.txt",
    #     "prompt_replace_path": "scripts_general/case_generator/prompt/prompt_template_for_backbone_replace.txt",
    #     "testify": {
    #         "system_dir": "new_case/testify/system",
    #         "replace_dir": "new_case/testify/replace",
    #         "start": 100,
    #         "end": 199,
    #         "seed": 10044,  
    #     },
    # }
}