# config.py

CONFIG = {
    "m0": [
        {
            "name": "M0首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 45,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-无意愿无能力-4w.json",
            "system_dir": "packages/M0_WN_AN/case/systemM0_WN_AN_4w",
            "replace_dir": "packages/M0_WN_AN/case/replaceM0_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10040,
            },
        },
        {
            "name": "M0首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 46,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-无意愿有能力-4w.json",
            "system_dir": "packages/M0_WN_AY/case/systemM0_WN_AY_4w",
            "replace_dir": "packages/M0_WN_AY/case/replaceM0_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10041,
            },
        },
        {
            "name": "M0首催_BP_易跳票客户",
            "enabled": True,
            "seed": 47,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-易跳票客户-4w.json",
            "system_dir": "packages/M0_BP/case/systemM0_BP_4w",
            "replace_dir": "packages/M0_BP/case/replaceM0_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10042,
            },
        },
        {
            "name": "M0首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 48,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有意愿无能力-4w.json",
            "system_dir": "packages/M0_WY_AN/case/systemM0_WY_AN_4w",
            "replace_dir": "packages/M0_WY_AN/case/replaceM0_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 49,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有意愿有能力-4w.json",
            "system_dir": "packages/M0_WY_AY/case/systemM0_WY_AY_4w",
            "replace_dir": "packages/M0_WY_AY/case/replaceM0_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10044,
            },
        },
        {
            "name": "M0首催_CR_有投诉风险",
            "enabled": True,
            "seed": 50,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有投诉风险-4w.json",
            "system_dir": "packages/M0_CR/case/systemM0_CR_4w",
            "replace_dir": "packages/M0_CR/case/replaceM0_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10045,
            },
        },
    ],
    "m0_follow": [
        {
            "name": "M0跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 51,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M0_follow_WN_AN/case/systemM0_follow_WN_AN_2w",
            "replace_dir": "packages/M0_follow_WN_AN/case/replaceM0_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10046,
            },
        },
        {
            "name": "M0跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 52,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M0_follow_WN_AY/case/systemM0_follow_WN_AY_2w",
            "replace_dir": "packages/M0_follow_WN_AY/case/replaceM0_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10047,
            },
        },
        {
            "name": "M0跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 53,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-易跳票客户-2w.json",
            "system_dir": "packages/M0_follow_BP/case/systemM0_follow_BP_2w",
            "replace_dir": "packages/M0_follow_BP/case/replaceM0_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10048,
            },
        },
        {
            "name": "M0跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 54,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M0_follow_WY_AN/case/systemM0_follow_WY_AN_2w",
            "replace_dir": "packages/M0_follow_WY_AN/case/replaceM0_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10049,
            },
        },
        {
            "name": "M0跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 55,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M0_follow_WY_AY/case/systemM0_follow_WY_AY_2w",
            "replace_dir": "packages/M0_follow_WY_AY/case/replaceM0_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10050,
            },
        },
        {
            "name": "M0跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 56,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-follow-有投诉风险-2w.json",
            "system_dir": "packages/M0_follow_CR/case/systemM0_follow_CR_2w",
            "replace_dir": "packages/M0_follow_CR/case/replaceM0_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M0_follow/M0_follow_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10051,
            },
        },
    ],
    "m1": {
        "name": "S1首催",
        "enabled": True,
        "seed": 39,
        "total_cases": 60000,
        "combinations_path": "packages/combinations/combinations-S1-6w.json",
        "system_dir": "packages/S1/systemS1-6w",
        "replace_dir": "packages/S1/replaceS1-6w",
        "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-0918.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify_case/replace",
            "start": 200,
            "end": 300,
            "seed": 10041,  
        },
    },
    "m1_follow": [
        {
            "name": "M1跟催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 57,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-无意愿无能力-2w.json",
            "system_dir": "packages/M1_follow_WN_AN/case/systemM1_follow_WN_AN_2w",
            "replace_dir": "packages/M1_follow_WN_AN/case/replaceM1_follow_WN_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10052,
            },
        },
        {
            "name": "M1跟催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 58,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-无意愿有能力-2w.json",
            "system_dir": "packages/M1_follow_WN_AY/case/systemM1_follow_WN_AY_2w",
            "replace_dir": "packages/M1_follow_WN_AY/case/replaceM1_follow_WN_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10053,
            },
        },
        {
            "name": "M1跟催_BP_易跳票客户",
            "enabled": True,
            "seed": 59,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-易跳票客户-2w.json",
            "system_dir": "packages/M1_follow_BP/case/systemM1_follow_BP_2w",
            "replace_dir": "packages/M1_follow_BP/case/replaceM1_follow_BP_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10054,
            },
        },
        {
            "name": "M1跟催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 60,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-有意愿无能力-2w.json",
            "system_dir": "packages/M1_follow_WY_AN/case/systemM1_follow_WY_AN_2w",
            "replace_dir": "packages/M1_follow_WY_AN/case/replaceM1_follow_WY_AN_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10055,
            },
        },
        {
            "name": "M1跟催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 61,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-有意愿有能力-2w.json",
            "system_dir": "packages/M1_follow_WY_AY/case/systemM1_follow_WY_AY_2w",
            "replace_dir": "packages/M1_follow_WY_AY/case/replaceM1_follow_WY_AY_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10056,
            },
        },
        {
            "name": "M1跟催_CR_有投诉风险",
            "enabled": True,
            "seed": 62,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M1-follow-有投诉风险-2w.json",
            "system_dir": "packages/M1_follow_CR/case/systemM1_follow_CR_2w",
            "replace_dir": "packages/M1_follow_CR/case/replaceM1_follow_CR_2w",
            "prompt_system_path": "datas/prompt_agent/M1_follow/M1_follow_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10057,
            },
        },
    ],
    "m2": {
        "name": "S1首催",
        "enabled": True,
        "seed": 39,
        "total_cases": 60000,
        "combinations_path": "packages/combinations/combinations-S1-6w.json",
        "system_dir": "packages/S1/systemS1-6w",
        "replace_dir": "packages/S1/replaceS1-6w",
        "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-0918.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify_case/replace",
            "start": 200,
            "end": 300,
            "seed": 10041,  
        },
    },
    "m2_follow": {
        "name": "S1跟催",
        "enabled": True,
        "seed": 35,
        "total_cases": 20000,
        "combinations_path": "packages/combinations/combinations-S1-follow-2w.json",
        "system_dir": "packages/S1/systemS1-follow-2w",
        "replace_dir": "packages/S1/replaceS1-follow-2w",
        "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-follow-0918.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify_case/replace",
            "start": 300,
            "end": 400,
            "seed": 10042,  
        },
    },
    "m3_plus": {
        "name": "S1首催",
        "enabled": True,
        "seed": 39,
        "total_cases": 60000,
        "combinations_path": "packages/combinations/combinations-S1-6w.json",
        "system_dir": "packages/S1/systemS1-6w",
        "replace_dir": "packages/S1/replaceS1-6w",
        "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-0918.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify_case/replace",
            "start": 200,
            "end": 300,
            "seed": 10041,  
        },
    },
    "m3_plus_follow": {
        "name": "S1跟催",
        "enabled": True,
        "seed": 35,
        "total_cases": 20000,
        "combinations_path": "packages/combinations/combinations-S1-follow-2w.json",
        "system_dir": "packages/S1/systemS1-follow-2w",
        "replace_dir": "packages/S1/replaceS1-follow-2w",
        "prompt_system_path": "scripts_general/case_generator/prompt/S1_due/prompt_template_for_system-S1-new-follow-0918.txt",
        "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
        "testify": {
            "system_dir": "packages/testify_case/system",
            "replace_dir": "packages/testify_case/replace",
            "start": 300,
            "end": 400,
            "seed": 10042,  
        },
    }
}