# config.py
# 同一个模块若有多套 case 配置，写成 list 即可，
# run.py 会依次遍历执行；只有一套时写 dict 也兼容。

CONFIG = {
    "m0": [
        {
            "name": "M0首催_WN_AN_无意愿无能力",
            "enabled": True,
            "seed": 45,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-无意愿无能力-4w.json",
            "system_dir": "packages/M0_WN_AN/case/systemM0_WN_AN_4w",
            "replace_dir": "packages/M0_WN_AN/case/replaceM0_WN_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 46,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-无意愿有能力-4w.json",
            "system_dir": "packages/M0_WN_AY/case/systemM0_WN_AY_4w",
            "replace_dir": "packages/M0_WN_AY/case/replaceM0_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_无意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_BP_易跳票客户",
            "enabled": True,
            "seed": 47,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-易跳票客户-4w.json",
            "system_dir": "packages/M0_BP/case/systemM0_BP_4w",
            "replace_dir": "packages/M0_BP/case/replaceM0_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_易跳票客户.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 48,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有意愿无能力-4w.json",
            "system_dir": "packages/M0_WY_AN/case/systemM0_WY_AN_4w",
            "replace_dir": "packages/M0_WY_AN/case/replaceM0_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿无能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 49,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有意愿有能力-4w.json",
            "system_dir": "packages/M0_WY_AY/case/systemM0_WY_AY_4w",
            "replace_dir": "packages/M0_WY_AY/case/replaceM0_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有意愿有能力.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
        {
            "name": "M0首催_CR_有投诉风险",
            "enabled": True,
            "seed": 50,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M0-有投诉风险-4w.json",
            "system_dir": "packages/M0_CR/case/systemM0_CR_4w",
            "replace_dir": "packages/M0_CR/case/replaceM0_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M0/M0_0918_有投诉风险.txt",
            "prompt_replace_path": "datas/prompt_agent/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 0,
                "end": 100,
                "seed": 10043,
            },
        },
    ]
}
