# config.py
# 同一个模块若有多套 case 配置，写成 list 即可，
# run.py 会依次遍历执行；只有一套时写 dict 也兼容。

CONFIG = {
    "m3_plus": [
        {
            "name": "M3plus_跟催_协商还款",
            "enabled": True,
            "seed": 112,
            "total_cases": 40,
            "combinations_path": "datas/suning_backend_0924/case/combinations/combinations-M3plus-follow-协商还款-4w.json",
            "system_dir": "datas/suning_backend_0924/case/systemM3plus_follow_DS_4w",
            "replace_dir": "datas/suning_backend_0924/case/replaceM3plus_follow_DS_4w",
            "prompt_system_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_system_跟催_协商还款.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "datas/suning_backend_0924/case/testify_case/system",
                "replace_dir": "datas/suning_backend_0924/case/testify_case/replace",
                "start": 0,
                "end": 99,
                "seed": 10112,
            },
        },
        {
            "name": "M3plus首催_WN_AY_无意愿有能力",
            "enabled": True,
            "seed": 113,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M3plus-无意愿有能力-4w.json",
            "system_dir": "packages/M3plus_WN_AY/case/systemM3plus_WN_AY_4w",
            "replace_dir": "packages/M3plus_WN_AY/case/replaceM3plus_WN_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_无意愿有能力.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 100,
                "end": 199,
                "seed": 10113,
            },
        },
        {
            "name": "M3plus首催_BP_易跳票客户",
            "enabled": True,
            "seed": 114,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M3plus-易跳票客户-4w.json",
            "system_dir": "packages/M3plus_BP/case/systemM3plus_BP_4w",
            "replace_dir": "packages/M3plus_BP/case/replaceM3plus_BP_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_易跳票客户.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 200,
                "end": 299,
                "seed": 10114,
            },
        },
        {
            "name": "M3plus首催_WY_AN_有意愿无能力",
            "enabled": True,
            "seed": 115,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M3plus-有意愿无能力-4w.json",
            "system_dir": "packages/M3plus_WY_AN/case/systemM3plus_WY_AN_4w",
            "replace_dir": "packages/M3plus_WY_AN/case/replaceM3plus_WY_AN_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有意愿无能力.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 300,
                "end": 399,
                "seed": 10115,
            },
        },
        {
            "name": "M3plus首催_WY_AY_有意愿有能力",
            "enabled": True,
            "seed": 116,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M3plus-有意愿有能力-4w.json",
            "system_dir": "packages/M3plus_WY_AY/case/systemM3plus_WY_AY_4w",
            "replace_dir": "packages/M3plus_WY_AY/case/replaceM3plus_WY_AY_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有意愿有能力.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 400,
                "end": 499,
                "seed": 10116,
            },
        },
        {
            "name": "M3plus首催_CR_有投诉风险",
            "enabled": True,
            "seed": 117,
            "total_cases": 40,
            "combinations_path": "packages/combinations/combinations-M3plus-有投诉风险-4w.json",
            "system_dir": "packages/M3plus_CR/case/systemM3plus_CR_4w",
            "replace_dir": "packages/M3plus_CR/case/replaceM3plus_CR_4w",
            "prompt_system_path": "datas/prompt_agent/M3+/M3+_0923_有投诉风险.txt",
            "prompt_replace_path": "datas/suning_backend_0924/case_gr_Suning-backend/prompt_template_for_backbone_replace.txt",
            "testify": {
                "system_dir": "packages/testify_case/system",
                "replace_dir": "packages/testify_case/replace",
                "start": 500,
                "end": 599,
                "seed": 10117,
            },
        },
    ]
}
